# Generated by Django 4.2.5 on 2023-10-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('age', models.IntegerField(verbose_name='age')),
                ('gender', models.CharField(max_length=30, verbose_name='gender')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['username'],
            },
        ),
    ]
